### ISSUE TITLE
error when testing magenta, help?

### ISSUE THREAD

**Issue by brisker** [hpssjellis/google-magenta-midi-music-on-linux-hello-world#2]
I try to run bazel test, but why getting this error related to protobuf, help?

(magenta) jcc@jcc:~/magenta$ bazel test //magenta/...
ERROR: /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.
ERROR: package contains errors: magenta/protobuf.
ERROR: error loading package 'magenta/protobuf': Extension 'protobuf.bzl' has errors.
INFO: Elapsed time: 0.246s
ERROR: Couldn't start the build. Unable to run tests.

And if I direcly import magenta , I got this error :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "magenta/__init__.py", line 26, in <module>
    import magenta.common.concurrency
  File "magenta/common/__init__.py", line 17, in <module>
    from sequence_example_lib import get_padded_batch
  File "magenta/common/sequence_example_lib.py", line 16, in <module>
    import tensorflow as tf
  File "/home/jcc/anaconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/jcc/anaconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jcc/anaconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/jcc/anaconda2/envs/magenta/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 964, in <module>
    options=None),
  File "/home/jcc/anaconda2/envs/magenta/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 505, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"

**Comment by hpssjellis** [comment]
It was working two weeks ago. I can't test it right now since I have a
developmental site in operation. The errors are not the normal ones I see
such as an import error since a package is not installed.

Good luck not sure what to suggest.
